// trinhminhtriet
// https://triettrinh.com
// BTC Address: 16Qg7G26iXKTPeGPLxofyptjT7UF85fMa5
// Minimum deposit amount: 0.001 BTC

// CCI coded OBV

study("Cryplive_CCI_OBV", shorttitle="Cryplive_CCI_OBV")
src = close
length = input(20, minval=1, title="CCI Length")
threshold=input(0, title="CCI threshold for OBV coding")
lengthema=input(13, title="EMA length")
obv(src) => 
    cum(change(src) > 0 ? volume : change(src) < 0 ? -volume : 0*volume)
    
o=obv(src)
c=cci(src, length)
plot(o, color=c>=threshold?green:red, title="OBV", linewidth=1)
plot(ema(o,lengthema), color=orange, title="EMA OBV", linewidth=1)