// trinhminhtriet
// https://triettrinh.com
// BTC Address: 16Qg7G26iXKTPeGPLxofyptjT7UF85fMa5
// Minimum deposit amount: 0.001 BTC

study("Cryplive_Buy_Sell_Signal", overlay = true)

Factor=input(1, minval=1,maxval = 100)
Pd=input(7, minval=1,maxval = 100)


Up=hl2-(Factor*atr(Pd))
Dn=hl2+(Factor*atr(Pd))


TrendUp=close[1]>TrendUp[1]? max(Up,TrendUp[1]) : Up
TrendDown=close[1]<TrendDown[1]? min(Dn,TrendDown[1]) : Dn

Trend = close > TrendDown[1] ? 1: close< TrendUp[1]? -1: nz(Trend[1],1)
Tsl = Trend==1? TrendUp: TrendDown

linecolor = Trend == 1 ? green : red

// plot(Tsl, color = linecolor, style = line, linewidth = 2, title = "Cryplive_Snapex_Buy_Sell_Signal")

// plotshape(cross(close,Tsl) and close>Tsl, "Up Arrow", shape.triangleup, location.belowbar, green, 0, 0)
// plotshape(cross(Tsl,close) and close<Tsl, "Down Arrow", shape.triangledown , location.abovebar, red, 0, 0)

plotarrow(Trend == 1 and Trend[1] == -1 ? Trend : na, title="Up Entry Arrow", colorup=lime, maxheight=30, minheight=10, transp=0)
plotarrow(Trend == -1 and Trend[1] == 1 ? Trend : na, title="Down Entry Arrow", colordown=red, maxheight=30, minheight=10, transp=0)


//Cryplive_Support_Resistance
window1 = input(title='lookback window 1:', type=integer, defval=8)
window2 = input(title='lookback window 2:', type=integer, defval=21)

top1 = valuewhen(high >= highest(high, window1), high, 0)
bot1 = valuewhen(low <= lowest(low, window1), low, 0)
top2 = valuewhen(high >= highest(high, window2), high, 0)
bot2 = valuewhen(low <= lowest(low, window2), low, 0)

t1 = plot(top1, color=top1 != top1[1] ? na : red, title='Resistance 1')
t2 = plot(top2, color=top2 != top2[1] ? na : red, title='Resistance 2')

b1 = plot(bot1, color=bot1 != bot1[1] ? na : green, title='Support 1')
b2 = plot(bot2, color=bot2 != bot2[1] ? na : green, title='Support 2')

fill(t1, t2, color=orange, transp=80)
fill(b1, b2, color=olive, transp=80)
