// @version=4

// trinhminhtriet
// https://triettrinh.com
// BTC (>0.001): 16Qg7G26iXKTPeGPLxofyptjT7UF85fMa5
// ETH (>0.01): 0x8190e253a57d940ea9521f8bf398996c524927d9

// ADX

study("Cryplive_ADX_DI")

adxlen = input(9, title="ADX Smoothing")
dilen = input(14, title="DI Length")
ADX_Entry = input(22, title="ADX Entry")

//ADX
dirmov(len) =>
	up = change(high)
	down = -change(low)
	truerange = rma(tr, len)
	plus = fixnan(100 * rma(up > down and up > 0 ? up : 0, len) / truerange)
	minus = fixnan(100 * rma(down > up and down > 0 ? down : 0, len) / truerange)
	[plus, minus]

adx(dilen, adxlen) => 
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
	[adx, plus, minus]

[sig, up, down] = adx(dilen, adxlen)

plot(ADX_Entry, color=color.white, linewidth=1)
plot(sig, color=color.purple, linewidth=1, title="ADX")
plot(up, color=color.green, linewidth=1, title="+DI")
plot(down, color=color.red, linewidth=1, title="-DI")

bgcolor(down-up > 0 ? color.red : color.lime, transp=90)
bgcolor(crossup(up, down) ? color.lime : na, transp=40)
bgcolor(crossdown(up, down) ? color.red : na, transp=40)