// trinhminhtriet
// https://triettrinh.com
// BTC Address: 16Qg7G26iXKTPeGPLxofyptjT7UF85fMa5
// Minimum deposit amount: 0.001 BTC

study("Cryplive_Buy_Sell_Signal", overlay=true)

Factor=input(1, minval=1,maxval = 100)
Pd=input(7, minval=1,maxval = 100)


Up=hl2-(Factor*atr(Pd))
Dn=hl2+(Factor*atr(Pd))


TrendUp=close[1]>TrendUp[1]? max(Up,TrendUp[1]) : Up
TrendDown=close[1]<TrendDown[1]? min(Dn,TrendDown[1]) : Dn

Trend = close > TrendDown[1] ? 1: close< TrendUp[1]? -1: nz(Trend[1],1)
Tsl = Trend==1? TrendUp: TrendDown

linecolor = Trend == 1 ? green : red

// plot(Tsl, color = linecolor, style = line, linewidth = 2, title = "Cryplive_Snapex_Buy_Sell_Signal")

// plotshape(cross(close,Tsl) and close>Tsl, "Up Arrow", shape.triangleup, location.belowbar, green, 0, 0)
// plotshape(cross(Tsl,close) and close<Tsl, "Down Arrow", shape.triangledown , location.abovebar, red, 0, 0)

plotarrow(Trend == 1 and Trend[1] == -1 ? Trend : na, title="Up Entry Arrow", colorup=lime, maxheight=30, minheight=10, transp=0)
plotarrow(Trend == -1 and Trend[1] == 1 ? Trend : na, title="Down Entry Arrow", colordown=red, maxheight=30, minheight=10, transp=0)


// BB input
BB_length = input(21, minval=1, title="BB Length")
BB_sdev = input(2.0, minval=0.001, maxval=50, title="StdDev")
OutBBThreshold = input(80, minval=1, title="Out BB Threshold")

// drawing BB
dev = BB_sdev * stdev(close, BB_length)
BB_basic = sma(close, BB_length)
BB_upper = BB_basic + dev
BB_lower = BB_basic - dev

BB_basic_up = BB_basic > BB_basic[1]
BB_basic_down = BB_basic < BB_basic[1]
BB_basic_color = BB_basic_up ? green : BB_basic_down ? red : blue

plot(BB_upper, title="BB Upper", color=BB_basic_color, linewidth=1)
plot(BB_lower, title="BB Lower", color=BB_basic_color, linewidth=1)
plot(BB_basic, title="BB Basic", color=BB_basic_color, linewidth=1)


//MAs
plot(ema(close,200), title="EMA200",color = red, linewidth = 1, transp=80)
plot(ema(close,100), title="EMA100",color = orange, linewidth = 1, transp=80)
plot(sma(close,50), title="EMA50",color = yellow, linewidth = 1, transp=80)
plot(sma(close,13), title="EMA13",color = yellow, linewidth = 1, transp=80)
plot(sma(close,5), title="EMA5",color = yellow, linewidth = 1, transp=80)